### ISSUE TITLE
Manual user checklist

### ISSUE THREAD

**Issue by tamsinforbes** [moj-analytical-services/user-guidance#359]
At this stage we just want a manual user checklist for users to check before they merge into `main`; any follow up notifications by email/slack could be developed later. 

> As a analyst and engineer I want to know if I've completed all requirements, so that I can merge to main successfully 

Add to the QuickReference page (and perhaps rejig the page) a manual checklist for users when they are merging to main; a list of things they should have done: `Checklist before raising a PR to merge to main`

Should include, but not limited to

- [ ] Dev models have passed the `deploy-dev` workflow (this will catch linting and tests if any
- [ ] Dev models include sufficient tests, which have all  all passed (we highly recommend tests; don't really want models in `prod` that don't have tests - cf `probation_referrals`) 
- [ ] Models are ready for data consumers to use (without fear of breaking changes to come: ie data consumers can begin to build downstream with confidence)
- [ ] Model database has a schedule set in `dbt_project.yml` (here only and not also in model config file/block)

A user project does not need to be finished for some models to be merged into `main`/`prod`. For instance a large project may have stages at which it is reasonable to release the so far completed models to `prod`. We should make this clear as we want to get stuff into `prod` as soon as it is ready for use.
